### ISSUE TITLE
Why placemarkFromCoordinates return a list since I'm providing only one coordinate? And why doesn't the plugin require a maps api key?

### ISSUE THREAD

**Issue by dpedrinha** [Baseflow/flutter-geocoding#101]
## 💬 Questions and Help

Basically what the title says.

`placemarkFromCoordinates` require only one coordinate, why does it return a `List<Placemark>` with multiple `Placemarks`?

Also, usually geocoding plugins ask for a `google maps api key` so it can avoid the systems restrictions. Would be great to have this option.

And last, is this project still being supported? Because I see a lot of old open issues with no replies and it concerns me if the devs are still working on this project.

Best regards

**Comment by bagus-repository** [comment]
It was the behavior of Google Geocoding API will return a list of place around provided coordinate, from [Google Geocoder](https://developer.android.com/reference/android/location/Geocoder#getFromLocation(double,%20double,%20int,%20android.location.Geocoder.GeocodeListener)).

Yes sure, I hope there is option to pass google API to control metric/billing by ourselves

**Comment by tijanirf** [comment]
This is precisely my concern, my company provided Google Maps API key for extensive use so it makes sense to give us the option to use our API key.

**Comment by mvanbeusekom** [comment]
Hi @dpedrinha,

First of all apologies for the belated reply. This plugin is still being supported however due to company restrictions we were not able to spend the amount of time necessary to go through all issue. Recent reorganisations allow us to structurally spend time on our open-source projects and thus allowing us to work through the issue backlog.

To answer your questions:

1. Since the Apple and Google APIs cannot always guarantee an exact address for the supplied coordinates a list of nearby addresses is returned. It is up to the consuming parties to filter out the best result. More details can be found in the respective native documentation ([Apple](https://developer.apple.com/documentation/corelocation/clgeocodecompletionhandler?language=objc), [Android](https://developer.android.com/reference/android/location/Geocoder.GeocodeListener#onGeocode(java.util.List%3Candroid.location.Address%3E))).
2. The Geocoder plugin is a simple wrapper around the native `CLGeocoder` (on iOS) and `Geocoder` (on Android) SDKs. These SDKs are supplied along side the operating system and are free to use (given certain restrictions in the form of rate limitation). These SDKs are available on all Android and iOS devices and offer limited functionality. We have thought about adapting other SDKs (e.g. payed Google Maps, HERE or MapBox), however those services already offer their own Flutter SDKs with much more functionality. Since people are paying for certain services, they'd most likely want to have access to all features and not the limited subset the Geocoding plugin offers. Also we cannot guarantee support for third party premium products.
