### ISSUE TITLE
How to store Placemark into Firebase with json_serializable / custom JsonConverter?

### ISSUE THREAD

**Issue by giorgio79** [Baseflow/flutter-geocoding#115]
I am trying to store a Placemark from the [Geolocator][1] plugin  to Firebase with json_serializable, but having problem creating a JsonConverter similar to [Geopoint][2]

I tried this so far
```
class PlacemarkConverter implements 

    JsonConverter<Placemark, Placemark> {
      const PlacemarkConverter();
    
      @override
      Placemark fromJson(map) {
        return Placemark.fromMap(map);
      }
    
      @override
      Placemark toJson(Placemark placemark) => placemark;
    }

```

but getting

> E/flutter (17813): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)]
> Unhandled Exception: type '_InternalLinkedHashMap<String, dynamic>' is
> not a subtype of type 'Placemark' in type cast

  [1]: https://pub.dev/packages/geolocator
  [2]: https://stackoverflow.com/questions/61707320/how-to-serialize-geopoint-using-dart-json-serializable-package

**Comment by JeroenWeener** [comment]
Hi @giorgio79, thank you for reaching out!

From the link to StackOverflow you sent, it seems that Firebase has a `GeoPoint` class that matches one-to-one with the `GeoPoint` class that is used by the OP of that post. As our plugin has a `Placemark` class with a different structure, you will need to implement the translation yourself.

```dart
class PlacemarkConverter implements JsonConverter<Placemark, GeoPoint> {
      const PlacemarkConverter();
    
      @override
      Placemark fromJson(Geopoint geoPoint) => Placemark.fromGeoPoint(geoPoint);
    
      @override
      GeoPoint toJson(Placemark placemark) => placemark.toGeoPoint();
}
```


ps.

You mention you are trying to store a `Placemark` object from the `flutter-geolocator` plugin. I am assuming you confuse that plugin with `flutter-geocoding`, as `flutter-geolocator` does not contain an object `Placemark` ever since the split in `flutter-geolocator` version `6.0.0`.


Please let me know if this resolves your issue or if you need further assistance.

**Comment by giorgio79** [comment]
Thx Jeroen, have to admit I don't remember this issue. I was just starting out in Flutter and raised a lot of dumb questions. Thanks for your reply. 🙂

**Comment by JeroenWeener** [comment]
There is no such thing as dumb questions @giorgio79 ;) Only progress on your understanding of programming 👍
