### ISSUE TITLE
I have proplem in network but my connection is right it didn't work never please help me

### ISSUE THREAD

**Issue by alim93593** [Baseflow/flutter-geocoding#126]
### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @alim93593,

I will be closing this issue due to lack of information. Without the requested information we are not able to help. If you are still experiencing problems using the Geocoding plugin feel free to create a new [issue](https://github.com/Baseflow/flutter-geocoding/issues/new/choose) and make sure to provide all requested information.
