### ISSUE TITLE
[Bug]: Unhandled Exception: Could not find any result for the supplied address or coordinates. 

### ISSUE THREAD

**Issue by Zeekoh23** [Baseflow/flutter-geocoding#166]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geocoding/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geocoding/blob/main/geocoding/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [X] iOS

### Steps to reproduce

1. I added an address in this code to get the coordinates.
  List<Location> locations = await locationFromAddress(
              merchant.address!,
              localeIdentifier: "en",
            );

### Expected results

It is meant to get the actual coordinates.

### Actual results

Unhandled Exception: Could not find any result for the supplied address or coordinates.

### Code sample

List<Location> locations = await locationFromAddress(
              merchant.address!,
              localeIdentifier: "en",
            );

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

latest version

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by Zeekoh23** [comment]
Android works well

**Comment by pravin-brovitech** [comment]
Execution failed for task ':geocoding_android:processDebugManifest'.
> Error while evaluating property 'packageOverride' of task ':geocoding_android:processDebugManifest'
   > Failed to calculate the value of task ':geocoding_android:processDebugManifest' property 'packageOverride'.
      > Failed to query the value of property 'applicationId'.
         > org.xml.sax.SAXParseException; systemId: file:/Users/vivent-app/.pub-cache/hosted/pub.dev/geocoding_android-2.1.2/android/src/main/AndroidManifest.xml; lineNumber: 3; columnNumber: 1; Element type "manifest" must be followed by either attribute specifications, ">" or "/>".
mac book error in windows its working

**Comment by TimHoogstrate** [comment]
Dear @pravin-brovitech,

I suggest you to update to the latest version.

@Zeekoh23,

Can you send us the adres that you are testing?

Kind regards,

**Comment by rBergCode** [comment]
I also have this issue. Everything worked yesterday.
I tried with "Quai Wilson 47, 1211 Genève".
How can I know if I passed the request limit ?

**Comment by mvanbeusekom** [comment]
Hi @rBergCode, 

If this works on a different device with the same OS, you are probably hitting the rate limit of the API on that OS. However this would result in a `IO_ERROR` and not the `Unhandled Exception: Could not find any result for the supplied address or coordinates.` mentioned by the original poster. Unfortunately there is no option to retrieve more detailed information about the request limit other than catching the `IO_ERROR`.

@Zeekoh23, since the geocoding plugin relies on the native APIs provided by the underlying OS, it is possible that an address can be found on Android, but not on iOS. On Android we know that the Google Maps API is utilized under the hood and it is more flexible in parsing the address string compared to the iOS counterpart. Unfortunately there is nothing we can do about this.

I will be closing this issue as it is out of our hands.
