### ISSUE TITLE
[Question]: Is geocoding_v3.0.1 going to be deployed to pub.dev anytime soon?

### ISSUE THREAD

**Issue by kterto** [Baseflow/flutter-geocoding#233]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geocoding/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geocoding/blob/main/geocoding/README.md).

### Please select for which platform(s) you need help

- [x] Android
- [X] iOS

### Your question

In order to comply with the ITMS-91053 apple requirements, starting in May 1st, the plugin needs to present a privacy manifest as it uses NSUserDefaults API. As I could see, there is a Tag pointing to geocoding_v3.0.1, that adds the privacy manifest, (although I couldn't be sure if the manifest is complying with requirements). Since the deadline is approaching, is it any intension to deploy a version of the app including the privacy manifest to pub.dev? 

### Version

2.2.0

**Comment by mvanbeusekom** [comment]
Hi @kterto,

The privacy manifest implementation is added to the `geocoding_ios` packages (which the `geocoding` package depends on). 

Version 3.0.1 of the `geocoding_ios` package has been [released on 3/18/2024](https://pub.dev/packages/geocoding_ios/versions). Since the `geocoding` package uses the following constraint for the dependency on the `geocoding_ios` package: `geocoding_ios: ^3.0.0` (see [Package versioning](https://dart.dev/tools/pub/versioning#constraint-solving) for more details on how constraints are being resolved). The dependency should automatically be updated. 

If you experience problems, you might want to locally run `flutter pub upgrade` and check your `pubspec.lock` file to determine which version of the `geocoding_ios` is used on you local machine.
