### ISSUE TITLE
locationFromAddress() never returns on iOS

### ISSUE THREAD

**Issue by victorfaye** [Baseflow/flutter-geocoding#26]
Hi, I have a problem using locationFromAddress()

When building the following on iOS, the 1st print statment never returns. I've provided the address given in the usage example just to be sure that this wasn't the address that was failing.
There is no error message, just the app waiting for the 1st print to return. `print('coordinates received');` is never reached.

Any idea of what I could have missed?

```
import 'package:flutter/material.dart';
import 'package:geocoding/geocoding.dart';
void main() async {
  print(await locationFromAddress("Gronausestraat 710, Enschede"));
  print('coordinates received');
  runApp(MyApp());
}
```

**Comment by mvanbeusekom** [comment]
@victorfaye most likely the services are not started fully yet since your app hasn't been properly initialized yet. 

I noticed that you are running the commands before you executed the `runApp(MyApp());` line. I suggest you move the print statements to a location somewhere inside the `MyApp` class to ensure the Flutter App is fully initialized and method channels are correctly setup on the native platform.
