### ISSUE TITLE
placemarkFromCoordinates implementation is missing on WEB

### ISSUE THREAD

**Issue by RajuMuliyashiya** [Baseflow/flutter-geocoding#27]
Overflow on channel: flutter.baseflow.com/geocoding.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
Error: MissingPluginException(No implementation found for method placemarkFromCoordinates on channel flutter.baseflow.com/geocoding)

**Version:** geocoding: ^1.0.5

**Platform:** 
- WEB

**Comment by mvanbeusekom** [comment]
@RajuMuliyashiya geocoding doesn't support web, currently only Android and iOS are supported.

**Comment by RajuMuliyashiya** [comment]
@mvanbeusekom  In Future will you add web support on same?

**Comment by mvanbeusekom** [comment]
Yes I am planning to but I don't have any indication on when I will get around to adding the implementation.

**Comment by giorgio79** [comment]
I would be happy to chip in $20 Does that help?
Most likely a copy and paste exercise, eg https://gist.github.com/tyrauber/3351515

**Comment by giorgio79** [comment]
and some more https://stackoverflow.com/questions/64007456/flutter-web-reverse-geocoding

**Comment by giorgio79** [comment]
PS this one seems to claim Web support maybe, merging efforts would be good https://pub.dev/packages/google_geocoding

**Comment by JDDV** [comment]
Hi @RajuMuliyashiya , I just made a proposal about this topic. It would help out a lot if you could read the #69 proposal and react to it.
The main problem is that in contrary to Android and Apples geocoding service, a geocoding web service is free to an extend, but paid if you exceed a certain request limit. This problem is all explained in the proposal, and it would help us out a lot if you could react to it!
