### ISSUE TITLE
placemarkFromCoordinates fails and throws unimplemented exception 

### ISSUE THREAD

**Issue by mohamedzakaria974** [Baseflow/flutter-geocoding#54]
according to your docs it works https://github.com/baseflow/flutter-geocoding#api 
but plugin throws unimplemented exception 
https://github.com/Baseflow/flutter-geocoding/blob/4cd439485f827aec22d7ea3afc6af05b2ed0eb8c/geocoding_platform_interface/lib/src/geocoding_platform_interface.dart#L65-L72

**Comment by renrique92** [comment]
have the same error, any news?

**Comment by mvanbeusekom** [comment]
@mohamedzakaria974, @renrique92, it seems like you are depending directly on the `geocoding_platform_interface` package instead of the `geocoding` package.

The `geocoding_platform_interface` simply contains a contract which can be used by other plugin developers to provide platform specific implementations. You should never depend on this package in your app. Instead you should depend on the `geocoding` package which contains the implementation for the iOS and Android platforms.
